Comparison operators
ElenaLadutska/JS-tasks pull request #1
Opened 2022-08-06 09:01 UTC by ElenaLadutska

Added 6.08 and 8.08 deadline files

2022-08-08 18:32 UTC, kathrynowy requested changes

2022-08-08 18:32 UTC, kathrynowy commented on index.js
> +// if(a == 10){
use strict comparison

2022-08-08 18:32 UTC, kathrynowy commented on index.js
> +// };
write it in 1 line please

2022-08-08 18:32 UTC, kathrynowy commented on index.js
> +//   }else if(isNaN(min) === true){
do you need here === true?

2022-08-08 18:32 UTC, kathrynowy commented on index.js
> +// if(a == 0){
use strict comparison

2022-08-12 16:50 UTC, merged

2022-08-14 08:42 UTC, ElenaLadutska commented on index.js
> +// if(a == 10){
fixed

2022-08-14 08:42 UTC, ElenaLadutska commented on index.js
> +// if(a == 10){
const a = +prompt('Text a number, please');
(a === 10) ? alert('true') : alert('false');

2022-08-14 08:43 UTC, ElenaLadutska commented on index.js
> +// };
fixed

2022-08-14 08:44 UTC, ElenaLadutska commented on index.js
> +//   }else if(isNaN(min) === true){
no. deleted. fixed

2022-08-14 08:46 UTC, ElenaLadutska commented on index.js
> +// if(a == 0){
fixed
(a === 0) ? alert('true') : alert('false');